### ISSUE TITLE
hi your website is perfect but isnt suited to my very specific needs pls fix :)

### ISSUE THREAD

**Issue by mat1jaczyyy** [vaaski/w2g#8]
![image](https://user-images.githubusercontent.com/13300194/90954431-89f38a80-e474-11ea-98f9-db464c87f248.png)

we're using your thing to watch recorded uni study sessions and when we pause the screen dims so the board is hard to read, also the paused text obstructs it

pls gib setting where this can be gotten rid of thank, also exam is in 4 days so thats your deadline if you wanna be useful

**Comment by mat1jaczyyy** [comment]
also a copy link to video with current timestamp would do wonders for storing time points into our notes

**Comment by vaaski** [comment]
good ideas, will do tomorrow when i'm at work

**Comment by mat1jaczyyy** [comment]
ty babe

**Comment by vaaski** [comment]
while adding a setting to disable the overlay i discovered that youtube isn't consistent with their overlay.
here's a video without the "more videos" overlay while paused:

![image](https://user-images.githubusercontent.com/17879327/90977086-06ed3580-e543-11ea-8914-2d975c31a987.png)

and here is the same video with the overlay showing

![image](https://user-images.githubusercontent.com/17879327/90977117-5b90b080-e543-11ea-9683-487e064392d6.png)


not sure what causes it to be shown or hidden, but i can't control this from w2g. if you need that hidden too then i could write a small userscript to hide it @mat1jaczyyy

**Comment by mat1jaczyyy** [comment]
wtf i thought you web developers can do all kinds of jank stuff

i am disappoint

eh ok at least no text then

**Comment by vaaski** [comment]
well we can, but we cant fuck with iframes contents.
there's only `window.postMessage` with which you can send messages back and forth.

i was actually working on a tampermonkey script which would run directly on youtube.com/embed/ which could enable you to do cool things like mapping the global keyboard media skip keys to play the next video in the queue or skip 5s of the video. similarly it could inject some css to hide that overlay.

**Comment by vaaski** [comment]
assuming i didn't break anything, you should be able to put `w2gPreferences.noOverlay(true)` into the console and after a reload it won't show up. you can still see that it's supposed to be paused based on the fat player border.
@mat1jaczyyy

**Comment by mat1jaczyyy** [comment]
nice pogyou
can we copy og video link with timestamp now as well

**Comment by mat1jaczyyy** [comment]
also make it userfriendly not all my friends are console nerds

**Comment by vaaski** [comment]
was too lazy to write a ui for it
would you be happy with a bookmarklet?

also whatchu mean with og timestamp?
you mean respecting the timestamp from a youtube url that you pasted into w2g?

**Comment by mat1jaczyyy** [comment]
no just pls make a checkbox somewhere goddammit

no, i mean i click button and ur website send `https://youtu.be/aaaaaaaaaaa?t=<timestamp we're currently at>` into my clipboard

**Comment by vaaski** [comment]
the url bar now includes the timestamp, you can copy that

for the ui thing, eeeeehhh i could maybe look at it in my shift tomorrow

but before i dig too deep into this i gotta refactor it

**Comment by mat1jaczyyy** [comment]
🆗

**Comment by mat1jaczyyy** [comment]
reopen issue ree

**Comment by mat1jaczyyy** [comment]
thank you

**Comment by vaaski** [comment]
![image](https://user-images.githubusercontent.com/17879327/91078948-b27daf00-e643-11ea-8102-3469c690f003.png)

**Comment by vaaski** [comment]
am lazy doe
